version: '3.1'

services:
  api:
    image: juanfernandoct/calculapp.1.0.1
    restart: always
    ports:
     - 8000:8080

  newman:
    image: postman/newman
    restart: on-failure
    ports:
      - 8091:8095
    volumes:
      - /home/juan/Documents/MitoCode/DevOps/TrabajoFinal/newman:/etc/newman
    command:
      "run calculator.postman_collection.json"