version: '3.1'
#Api Calculadorda
services:
  api:
    image: juanfernandoct/calculapp.1.0.1
    restart: always
    ports:
     - 8080:8080
     
#Pruebas del API con Newman
  newman:
    image: postman/newman
    restart: on-failure
    ports: 
      - 8091:8095  
    volumes:
      - /home/juan/Documents/MitoCode/DevOps/TrabajoFinal/newman:/etc/newman      
    command:
       "run calculator.postman_collection.json"  
#    networks:
#      - calcnet 
#
#networks:      
#  calcnet:
#    driver: bridge
      
   
     